### ISSUE TITLE
Ajuste del mapa en summary

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/mibloque#75]
La idea es correr el mapa a la izquierda (centrado en el espacio disponible). para que el panel no lo tape al inicio (verificar si reducir el zoom)

**Comment by erikasv** [comment]
Cesar encontró esto, puede que sea útil: https://stackoverflow.com/questions/33614912/how-to-locate-leaflet-zoom-control-in-a-desired-position/33621034

**Comment by uamoreno** [comment]
Se dejó un pull request con una solución propuesta.

**Comment by uamoreno** [comment]
Se mezclo la solución en la rama develop, el polígono a mostrar sobre el mapa aparece 'centrado' con un padding de -600 en el eje x.
