### ISSUE TITLE
Metadado incorrecto

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/mibloque#76]
Cambiar metadato del indicador "Ecosistemas amenazados dentro del bloque" por el correcto, actualmente está saliendo "Riqueza de especies de importancia pesquera"

**Comment by uamoreno** [comment]
Se cambió el texto "Riqueza de especies de importancia pesquera" que aparecía en la presentación de "Ecosistemas amenazados dentro del bloque". Se tomó un backup el 20 de enero de 2020 con la actualizacion hecha a la base de datos.
